version: '2'

services:
  d-movie-gallery:
    build:
      context: .
      dockerfile: dockerfiles/app.docker.dev
    env_file: .env
    container_name: d-movie-gallery
    ports:
      - '${PORT}:3000'
    working_dir: /usr/src/app
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    networks:
      - default
      - bridge-network
networks:
  default:
    driver: bridge
  bridge-network:
    external: true
